# Generated by Django 3.2.8 on 2021-10-19 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reportdev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdevmodel',
            name='screenShot',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
