# Generated by Django 3.2.8 on 2021-10-19 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reportdev', '0002_reportdevmodel_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdevmodel',
            name='logCsvFile',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportdevmodel',
            name='screenShot',
            field=models.CharField(max_length=10000),
        ),
    ]
